#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
#    username: "sa"
#    password:
#    driver-class-name: org.h2.driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#    open-in-view: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
spring:
  datasource:
    url: jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa # DB 접속 username
    password: # DB 접속 password, 없음
    driver-class-name: org.h2.Driver # DB 접속 드라이버
  h2.console:
    enabled: true # 콘솔 사용 여부, 로컬에서 웹 브라우저로도 접속 가능
  jpa:
    hibernate:
      ddl-auto: create # 테이블을 자동으로 생성함
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # SQL 로그 출력
logging:
level:
  org.hibernate.SQL: debug # SQL 로그 출력을 위한 로그 레벨 조정
---
# 스프링 mysql 접근
# 무료 버전 on-profile 설정
# Modify options->Add VM options -> -Dspring.profiles.active=원하는 profile 추가

spring:
  config:
    activate:
      on-profile: dev
      #The following 1 profile is active: "dev"
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "Abcd1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect